universal:
  ЕГЭ: "Единый государственный экзамен"
  ОКСО: "Общероссийский классификатор специальностей по образованию"
  БВИ: "Без вступительных испытаний"
  ДВИ: "Дополнительные вступительные испытания"
  НИУ: "Национальный исследовательский университет"
  ФКН: "Факультет компьютерных наук"
  ФГН: "Факультет гуманитарных наук"
  ФЭН: "Факультет экономических наук"
  ФСН: "Факультет социальных наук"
  ФКИ: "Факультет креативных индустрий"
  ФББ: "Факультет биологии и биотехнологии"
  ВШБ: "Высшая школа бизнеса"
  МИЭМ: "Московский институт электроники и математики им. А.Н. Тихонова"
  МИЭФ: "Международный институт экономики и финансов"
  ШИЯ: "Школа иностранных языков"
