universal:
  ЕГЭ: "Единый государственный экзамен"
  ОКСО: "Общероссийский классификатор специальностей по образованию"
  БВИ: "Без вступительных испытаний"
  ДВИ: "Дополнительные вступительные испытания"
  НИУ: "Национальный исследовательский университет"
